name: LaundryUp
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.10.4







dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:          # â† baris ini WAJIB ada
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.2
  shared_preferences: ^2.3.0
  url_launcher: ^6.3.0
  url_launcher_web: ^2.3.1




dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_test:
    sdk: flutter



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/Logo-Main.png"
  min_sdk_android: 21

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/Logo-Main.png
    - assets/QRIS.png
    - assets/logo.png

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
